name: Update Flake

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual execution

jobs:
  update-flake:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake inputs
        run: nix flake update

      - name: Check if there are changes
        id: changes
        run: |
          if git diff --quiet flake.lock; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run flake check
        if: steps.changes.outputs.has_changes == 'true'
        run: nix flake check

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update flake inputs (${{ steps.date.outputs.date }})"
          title: "chore: update flake inputs (${{ steps.date.outputs.date }})"
          body: |
            ## Automated Package Update

            This PR was created automatically.

            ### Changes
            - Updated `flake.lock` file
            - Updated various packages to their latest versions

            ### Checklist
            - [ ] Verify that build completes successfully
            - [ ] Verify that configuration files work correctly
            - [ ] Verify that new package versions don't cause issues

            ### Notes
            It's recommended to test in your local environment before merging this PR:
            ```bash
            make build
            make switch
            ```

            Please merge after CI/CD checks pass and if there are no issues.
          branch: automated-flake-update-${{ steps.date.outputs.date }}
          delete-branch: true
          draft: false 